.extern _ZN5RiscV20handleEcallInterruptEv
.extern _ZN5RiscV20handleTimerInterruptEv
.extern _ZN5RiscV23handleExternalInterruptEv
.align 4
.global _ZN5RiscV16interruptRoutineEv
.type _ZN5RiscV16interruptRoutineEv, @function

_ZN5RiscV16interruptRoutineEv:
    j EcallInterrupt
    j TimerInterrupt
    .skip 28 #osatvlja prazno 7 ulaza u IVT
    j ExternalInterrupt
EcallInterrupt:
    addi sp, sp, -256
    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index*8(sp)
    .endr

    call _ZN5RiscV20handleEcallInterruptEv

    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index*8(sp)
    .endr
    addi sp, sp, 256

    sret
#Prekid od tajmera
TimerInterrupt:
    addi sp, sp, -256
    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index*8(sp)
    .endr

    call _ZN5RiscV20handleTimerInterruptEv

    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index*8(sp)
    .endr
    addi sp, sp, 256

    sret
#Spoljasnji prekid
ExternalInterrupt:
    addi sp, sp, -256
    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index*8(sp)
    .endr

    call _ZN5RiscV23handleExternalInterruptEv

    .irp index, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index*8(sp)
    .endr
    addi sp, sp, 256

    sret


